// Generates the browser-loadable locale bundle from the JSON source files.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const root = join(scriptDir, "..");
const localeDir = join(root, "src", "locales");
const outputPath = join(root, "src", "js", "locales.js");
const check = process.argv.includes("--check");
const expectedLanguages = ["de", "en", "es", "fr", "ja", "ru", "tr"];

const languages = {};
for (const name of readdirSync(localeDir).filter((name) => name.endsWith(".json")).sort()) {
  const code = name.replace(/\.json$/, "");
  languages[code] = JSON.parse(readFileSync(join(localeDir, name), "utf8"));
}

const actualLanguages = Object.keys(languages);
if (actualLanguages.join(",") !== expectedLanguages.join(",")) {
  throw new Error(`locale set mismatch: expected=${expectedLanguages} actual=${actualLanguages}`);
}

function flatten(value, prefix = "", output = new Map()) {
  for (const [key, child] of Object.entries(value)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (child && typeof child === "object" && !Array.isArray(child)) flatten(child, path, output);
    else output.set(path, child);
  }
  return output;
}

const reference = flatten(languages.en || {});
for (const [language, values] of Object.entries(languages)) {
  const keys = flatten(values);
  const missing = [...reference.keys()].filter((key) => !keys.has(key));
  const extra = [...keys.keys()].filter((key) => !reference.has(key));
  const empty = [...keys].filter(([, value]) => typeof value !== "string" || !value.trim());
  if (missing.length || extra.length || empty.length) {
    throw new Error(
      `${language}: missing=${missing.join(",")} extra=${extra.join(",")} empty=${empty.map(([key]) => key).join(",")}`,
    );
  }
}

const generated = `// Generated by scripts/generate-locales.mjs. Do not edit directly.\n` +
  `(function (global) {\n  global.HALITE_LOCALES = ${JSON.stringify(languages, null, 2)};\n` +
  `})(typeof window !== "undefined" ? window : globalThis);\n`;

if (check) {
  if (readFileSync(outputPath, "utf8") !== generated) {
    throw new Error("src/js/locales.js is stale; run npm run generate-locales");
  }
  console.log(`[locales] ${Object.keys(languages).length} languages, ${reference.size} keys: OK`);
} else {
  writeFileSync(outputPath, generated);
  console.log(`[locales] generated ${outputPath}`);
}
